export type NiveauId = "i" | "2" | "3";

export interface ComposantesThematique {
  thematique: string;
  declencheurs: Record<NiveauId, string[]>;
  etapes: {
    numero: number;
    nom: string;
    menaces: Record<NiveauId, string[]>;
    opportunites: Record<NiveauId, string[]>;
  }[];
}

export const composantesEnergie: ComposantesThematique = {
  thematique: "Gestion de l'énergie",
  declencheurs: {
    i: [
      "Se réveiller déjà fatigué",
      "Dormir trop peu pendant plusieurs jours",
      "Ressentir une baisse importante d'énergie en après-midi",
      "Avoir de la difficulté à se concentrer",
      "Manquer de motivation pour commencer une tâche",
      "Se sentir dépassé mentalement",
      "Avoir des douleurs physiques ou des tensions",
      "Avoir une surcharge mentale",
      "Faire trop d'activités sans pause",
      "Avoir l'impression de fonctionner sur le pilote automatique",
      "Manger rapidement ou irrégulièrement",
      "Se sentir épuisé après une petite tâche",
      "Avoir des pensées constantes qui empêchent le repos",
      "Se sentir coupable de ralentir",
      "Négliger ses besoins physiques",
      "Manquer de sommeil réparateur",
      "Sentir une perte d'intérêt générale",
      "Ne pas réussir à récupérer malgré le repos",
      "Se sentir vidé émotionnellement",
      "Vouloir tout faire en même temps",
    ],
    "2": [
      "Recevoir trop de demandes des autres",
      "Avoir de la difficulté à dire non",
      "Être sollicité constamment",
      "Vivre des conflits relationnels",
      "Se sentir responsable des émotions des autres",
      "Être entouré de personnes négatives",
      "Recevoir des attentes élevées",
      "Avoir l'impression de devoir performer socialement",
      "Être interrompu constamment",
      "Manquer de soutien dans son entourage",
      "Avoir une charge familiale importante",
      "Devoir gérer plusieurs besoins des autres",
      "Être dans une relation énergivore",
      "Recevoir des critiques fréquentes",
      "Se sentir obligé d'aider tout le monde",
      "Ne pas se sentir compris",
      "Vivre des tensions dans le couple",
      "Participer à trop d'activités sociales",
      "Être entouré de stress relationnel",
      "Sentir qu'on doit toujours être disponible",
    ],
    "3": [
      "Avoir un horaire surchargé",
      "Travailler dans un environnement stressant",
      "Être exposé constamment au bruit",
      "Manquer de temps pour récupérer",
      "Vivre dans un environnement désorganisé",
      "Avoir trop de responsabilités",
      "Être exposé à trop de stimulation numérique",
      "Avoir une pression de performance constante",
      "Manquer d'accès à des moments de calme",
      "Être dans un environnement rapide et exigeant",
      "Avoir des déplacements épuisants",
      "Être dans un milieu de travail instable",
      "Recevoir trop d'informations en même temps",
      "Ne pas avoir d'espace personnel",
      "Être dans un environnement peu motivant",
      "Avoir des obligations constantes",
      "Être exposé à des urgences fréquentes",
      "Manquer de structure dans son quotidien",
      "Avoir peu d'équilibre entre travail et repos",
      "Se sentir toujours en mode survie",
    ],
  },
  etapes: [
    {
      numero: 1,
      nom: "Observer",
      menaces: {
        i: [
          "Observer principalement sa fatigue",
          "Porter attention uniquement au manque d'énergie",
          "Observer constamment les tâches restantes",
          "Se concentrer sur les obligations",
          "Observer les signes de surcharge sans agir",
          "Ignorer les moments où l'énergie est meilleure",
          "Observer uniquement les problèmes physiques",
          "Porter attention aux imprévus stressants",
          "Observer son environnement comme épuisant",
          "Se concentrer sur la pression du temps",
          "Observer uniquement ce qui vide l'énergie",
          "Ignorer les besoins de récupération",
          "Observer les attentes des autres avant ses besoins",
          "Porter attention aux interruptions constantes",
          "Observer le manque de temps libre",
          "Se concentrer sur les performances à maintenir",
          "Observer ses limites comme un problème",
          "Ignorer les signes de tension physique",
          "Observer son quotidien comme une course constante",
          "Porter attention uniquement à ce qui doit être fait",
        ],
        "2": [],
        "3": [],
      },
      opportunites: {
        i: [
          "Observer son niveau d'énergie réel",
          "Reconnaître les signes de fatigue",
          "Observer les moments où l'énergie est meilleure",
          "Identifier les activités énergivores",
          "Observer les activités ressourçantes",
          "Porter attention à son sommeil",
          "Observer les besoins de récupération",
          "Reconnaître les limites de son corps",
          "Observer les impacts du stress",
          "Porter attention aux moments de calme",
          "Observer les habitudes qui aident l'énergie",
          "Identifier les sources de motivation",
          "Observer les relations qui soutiennent",
          "Reconnaître les signes de surcharge",
          "Observer les impacts de l'alimentation",
          "Identifier les environnements épuisants",
          "Observer les effets positifs des pauses",
          "Reconnaître les besoins émotionnels",
          "Observer son rythme personnel",
          "Porter attention aux moments de bien-être",
        ],
        "2": [],
        "3": [],
      },
    },
    {
      numero: 2,
      nom: "Prédire",
      menaces: {
        i: [
          "Penser qu'il faut toujours continuer",
          "Croire que ralentir est une faiblesse",
          "Imaginer perdre le contrôle si l'on se repose",
          "Penser qu'on doit tout gérer seul",
          "Croire qu'on n'a pas le droit d'être fatigué",
          "Prévoir des conséquences négatives au repos",
          "Penser qu'on doit être productif constamment",
          "Imaginer décevoir les autres",
          "Croire qu'il faut dépasser ses limites",
          "Penser qu'on ne peut pas ralentir",
          "Imaginer qu'on sera jugé si l'on prend une pause",
          "Croire que les besoins personnels sont secondaires",
          "Prévoir davantage de problèmes si l'on arrête",
          "Penser qu'on doit toujours performer",
          "Imaginer perdre des opportunités en se reposant",
          "Croire que récupérer fait perdre du temps",
          "Penser qu'on doit être disponible constamment",
          "Imaginer qu'on ne réussira jamais à suivre le rythme",
          "Croire qu'on doit terminer toutes les tâches immédiatement",
          "Prévoir uniquement les obligations sans récupération",
        ],
        "2": [],
        "3": [],
      },
      opportunites: {
        i: [
          "Penser que le repos aide la récupération",
          "Croire qu'il est normal d'avoir des limites",
          "Imaginer retrouver de l'énergie progressivement",
          "Penser qu'on peut ajuster son rythme",
          "Croire que ralentir peut améliorer l'efficacité",
          "Prévoir des solutions équilibrées",
          "Penser qu'on peut demander de l'aide",
          "Croire qu'on mérite du repos",
          "Imaginer des stratégies plus réalistes",
          "Penser qu'on peut respecter ses besoins",
          "Croire qu'il est possible d'avoir un meilleur équilibre",
          "Prévoir des moments de récupération bénéfiques",
          "Penser qu'on peut prioriser différemment",
          "Imaginer des journées moins surchargées",
          "Croire que l'énergie peut se reconstruire",
          "Penser qu'on peut fonctionner autrement",
          "Prévoir des résultats positifs avec des ajustements",
          "Imaginer plus de stabilité énergétique",
          "Croire qu'on peut protéger son énergie",
          "Penser qu'il est possible de ralentir sans échouer",
        ],
        "2": [],
        "3": [],
      },
    },
    {
      numero: 3,
      nom: "Ressentir",
      menaces: {
        i: [
          "Ressentir de l'épuisement",
          "Ressentir du stress constant",
          "Ressentir de la frustration",
          "Ressentir de l'impuissance",
          "Ressentir de l'anxiété",
          "Ressentir de la culpabilité lorsqu'on ralentit",
          "Ressentir de la surcharge émotionnelle",
          "Ressentir de la pression intérieure",
          "Ressentir de l'irritabilité",
          "Ressentir du découragement",
          "Ressentir un vide d'énergie",
          "Ressentir une tension constante",
          "Ressentir de la fatigue émotionnelle",
          "Ressentir de l'inquiétude face aux responsabilités",
          "Ressentir une perte de motivation",
          "Ressentir de l'agitation mentale",
          "Ressentir une sensation d'urgence permanente",
          "Ressentir de la tristesse liée à l'épuisement",
          "Ressentir de la confusion mentale",
          "Ressentir un manque d'équilibre intérieur",
        ],
        "2": [],
        "3": [],
      },
      opportunites: {
        i: [
          "Ressentir du calme après une pause",
          "Ressentir du soulagement en ralentissant",
          "Ressentir de la légèreté émotionnelle",
          "Ressentir de la sérénité",
          "Ressentir de la sécurité intérieure",
          "Ressentir du repos mental",
          "Ressentir de la motivation retrouvée",
          "Ressentir du bien-être physique",
          "Ressentir de l'équilibre émotionnel",
          "Ressentir de la gratitude envers son corps",
          "Ressentir de l'apaisement",
          "Ressentir de l'énergie positive",
          "Ressentir de l'espoir",
          "Ressentir de la stabilité",
          "Ressentir du plaisir dans le repos",
          "Ressentir de la présence au moment présent",
          "Ressentir du confort émotionnel",
          "Ressentir de la confiance envers son rythme",
          "Ressentir de la détente",
          "Ressentir un meilleur équilibre intérieur",
        ],
        "2": [],
        "3": [],
      },
    },
    {
      numero: 4,
      nom: "Choisir",
      menaces: {
        i: [
          "Choisir de continuer malgré l'épuisement",
          "Choisir d'ignorer les besoins du corps",
          "Choisir de prioriser uniquement les obligations",
          "Choisir de ne pas ralentir",
          "Choisir de dépasser ses limites",
          "Choisir de rester disponible constamment",
          "Choisir de cacher sa fatigue",
          "Choisir de ne pas demander d'aide",
          "Choisir d'éviter les pauses",
          "Choisir de garder un rythme irréaliste",
          "Choisir de faire plaisir aux autres avant soi",
          "Choisir de fonctionner sous pression constante",
          "Choisir de maintenir des habitudes épuisantes",
          "Choisir d'accumuler les responsabilités",
          "Choisir de négliger le sommeil",
          "Choisir de repousser la récupération",
          "Choisir de minimiser ses besoins",
          "Choisir de rester dans la surcharge",
          "Choisir de ne pas écouter ses émotions",
          "Choisir de continuer sans ajustement",
        ],
        "2": [],
        "3": [],
      },
      opportunites: {
        i: [
          "Choisir de respecter ses limites",
          "Choisir de ralentir lorsque nécessaire",
          "Choisir de prioriser sa récupération",
          "Choisir de demander du soutien",
          "Choisir de protéger son énergie",
          "Choisir un rythme plus réaliste",
          "Choisir d'écouter son corps",
          "Choisir de faire des pauses régulières",
          "Choisir de réduire certaines obligations",
          "Choisir de mieux équilibrer ses journées",
          "Choisir de se prioriser davantage",
          "Choisir des activités ressourçantes",
          "Choisir d'ajuster ses attentes",
          "Choisir de mieux répartir son énergie",
          "Choisir un mode de vie plus équilibré",
          "Choisir des habitudes plus saines",
          "Choisir de ralentir sans culpabilité",
          "Choisir des relations moins énergivores",
          "Choisir de reconnaître ses besoins émotionnels",
          "Choisir de préserver sa stabilité intérieure",
        ],
        "2": [],
        "3": [],
      },
    },
    {
      numero: 5,
      nom: "Planifier",
      menaces: {
        i: [
          "Planifier trop d'activités",
          "Prévoir des horaires irréalistes",
          "Organiser ses journées sans pauses",
          "Prévoir uniquement les obligations",
          "Planifier selon les attentes des autres",
          "Ne pas prévoir de récupération",
          "Prévoir un rythme trop rapide",
          "Organiser des journées surchargées",
          "Planifier plusieurs tâches en même temps",
          "Prévoir peu de temps personnel",
          "Organiser des objectifs trop exigeants",
          "Prévoir constamment des urgences",
          "Ne pas planifier son sommeil",
          "Prévoir des activités énergivores sans équilibre",
          "Organiser son temps sans flexibilité",
          "Prévoir plus que ses capacités réelles",
          "Ne pas prévoir de soutien",
          "Organiser ses journées sous pression",
          "Prévoir peu de moments de calme",
          "Planifier sans tenir compte de son énergie réelle",
        ],
        "2": [],
        "3": [],
      },
      opportunites: {
        i: [
          "Planifier des pauses régulières",
          "Prévoir du temps de récupération",
          "Organiser un horaire plus équilibré",
          "Planifier selon son niveau d'énergie",
          "Prévoir des moments de calme",
          "Organiser ses priorités essentielles",
          "Prévoir des limites réalistes",
          "Planifier des activités ressourçantes",
          "Prévoir du soutien si nécessaire",
          "Organiser son sommeil adéquatement",
          "Prévoir des stratégies anti-surcharge",
          "Planifier des moments sans stimulation numérique",
          "Organiser ses tâches progressivement",
          "Prévoir du temps pour soi",
          "Planifier des activités physiques adaptées",
          "Prévoir des moments de plaisir",
          "Organiser un environnement plus apaisant",
          "Prévoir des stratégies de gestion du stress",
          "Planifier selon ses capacités réelles",
          "Prévoir des ajustements lorsque l'énergie baisse",
        ],
        "2": [],
        "3": [],
      },
    },
    {
      numero: 6,
      nom: "Agir",
      menaces: {
        i: [
          "Continuer malgré les signes d'épuisement",
          "Dormir insuffisamment",
          "Accepter trop de responsabilités",
          "Négliger les pauses",
          "Faire plusieurs tâches en même temps constamment",
          "Ignorer les besoins physiques",
          "Rester connecté aux écrans sans arrêt",
          "Reporter les moments de récupération",
          "Travailler au-delà de ses capacités",
          "Maintenir un rythme trop rapide",
          "Éviter les activités de récupération",
          "Surcharger ses journées",
          "Rester disponible constamment",
          "Négliger l'alimentation et l'hydratation",
          "Éviter de ralentir malgré la fatigue",
          "Se pousser sous pression",
          "Accumuler les obligations sans ajustement",
          "Continuer des habitudes énergivores",
          "Ne pas respecter ses limites",
          "Fonctionner en mode automatique constamment",
        ],
        "2": [],
        "3": [],
      },
      opportunites: {
        i: [
          "Faire des pauses régulièrement",
          "Dormir suffisamment",
          "Respecter ses limites physiques",
          "Réduire les activités énergivores",
          "Prendre du temps pour récupérer",
          "Maintenir une alimentation plus équilibrée",
          "Bouger selon son énergie réelle",
          "Pratiquer des activités apaisantes",
          "Répartir son énergie dans la journée",
          "Demander de l'aide lorsque nécessaire",
          "Prendre du temps sans stimulation numérique",
          "Maintenir un rythme plus stable",
          "Dire non à certaines demandes",
          "Faire une tâche à la fois",
          "Écouter les signaux de son corps",
          "Intégrer des moments de calme",
          "Ajuster son rythme selon sa fatigue",
          "Prioriser les activités importantes",
          "Maintenir des habitudes de récupération",
          "Respecter ses besoins émotionnels",
        ],
        "2": [],
        "3": [],
      },
    },
    {
      numero: 7,
      nom: "Évaluer",
      menaces: {
        i: [
          "Observer uniquement sa fatigue",
          "Minimiser les impacts de la surcharge",
          "Évaluer sa valeur selon sa productivité",
          "Ignorer les signes d'épuisement",
          "Se critiquer lorsqu'on ralentit",
          "Observer seulement ce qui reste à faire",
          "Minimiser les besoins de récupération",
          "Évaluer négativement ses limites",
          "Se comparer aux autres constamment",
          "Ignorer les effets positifs des pauses",
          "Observer uniquement les performances",
          "Évaluer ses journées comme insuffisantes",
          "Se concentrer sur les retards",
          "Minimiser les améliorations énergétiques",
          "Observer les pauses comme une perte de temps",
          "Évaluer négativement ses capacités physiques",
          "Ignorer les signaux émotionnels",
          "Observer uniquement les obligations accomplies",
          "Minimiser les effets du stress",
          "Évaluer ses résultats sans considérer son énergie",
        ],
        "2": [],
        "3": [],
      },
      opportunites: {
        i: [
          "Observer les effets positifs du repos",
          "Évaluer son niveau d'énergie quotidien",
          "Reconnaître les stratégies qui aident",
          "Observer les moments de surcharge",
          "Évaluer l'impact du sommeil",
          "Reconnaître ses limites avec respect",
          "Observer les effets du stress",
          "Évaluer l'équilibre entre activité et récupération",
          "Reconnaître les moments où l'on récupère mieux",
          "Observer les habitudes énergivores",
          "Évaluer les impacts des relations sur son énergie",
          "Observer les améliorations physiques",
          "Reconnaître les périodes plus équilibrées",
          "Évaluer les stratégies de gestion du temps",
          "Observer les effets des pauses",
          "Évaluer les ajustements nécessaires",
          "Reconnaître les signes de progression",
          "Observer les changements dans son humeur",
          "Évaluer ses capacités réelles",
          "Observer l'impact des nouvelles habitudes",
        ],
        "2": [],
        "3": [],
      },
    },
    {
      numero: 8,
      nom: "Apprendre",
      menaces: {
        i: [
          "Apprendre à ignorer ses limites",
          "Intégrer la surcharge comme normale",
          "Renforcer les habitudes d'épuisement",
          "Apprendre à fonctionner sous stress constant",
          "Intégrer le repos comme une perte de temps",
          "Renforcer le besoin de performance constante",
          "Apprendre à négliger ses besoins",
          "Intégrer un rythme irréaliste",
          "Renforcer les comportements de suradaptation",
          "Apprendre à dépasser constamment ses limites",
          "Intégrer l'idée qu'il faut toujours produire",
          "Renforcer les stratégies énergivores",
          "Apprendre à minimiser sa fatigue",
          "Intégrer un déséquilibre constant",
          "Renforcer le mode survie",
          "Apprendre à ne pas écouter son corps",
          "Intégrer le stress comme mode de fonctionnement",
          "Renforcer l'épuisement émotionnel",
          "Apprendre à prioriser uniquement les obligations",
          "Intégrer des habitudes de récupération insuffisantes",
        ],
        "2": [],
        "3": [],
      },
      opportunites: {
        i: [
          "Apprendre à respecter ses limites",
          "Intégrer des habitudes de récupération",
          "Développer un meilleur équilibre énergétique",
          "Apprendre à écouter son corps",
          "Intégrer l'importance du repos",
          "Développer des stratégies anti-surcharge",
          "Apprendre à ralentir sans culpabilité",
          "Intégrer un rythme plus réaliste",
          "Développer des habitudes plus équilibrées",
          "Apprendre à protéger son énergie",
          "Intégrer des périodes de récupération régulières",
          "Développer une meilleure gestion du stress",
          "Apprendre à prioriser l'essentiel",
          "Intégrer des stratégies de repos efficaces",
          "Développer une stabilité émotionnelle plus grande",
          "Apprendre à ajuster son rythme",
          "Intégrer des comportements plus respectueux de soi",
          "Développer des habitudes de vie plus saines",
          "Apprendre à reconnaître les signes de surcharge",
          "Intégrer une trajectoire plus équilibrée",
        ],
        "2": [],
        "3": [],
      },
    },
  ],
};

export const allComposantes: ComposantesThematique[] = [composantesEnergie];

export function getComposantes(thematique: string): ComposantesThematique | undefined {
  return allComposantes.find((c) => c.thematique === thematique);
}
