import type { MasterclassData } from "./index";

export const masterclassEnergie: MasterclassData = {
  slug: "energie",
  thematique: "Gestion de l'énergie",
  icon: "⚡",
  personnage: "Marc",
  parties: [
    {
      numero: 0,
      titre: "Introduction — Vivre selon son potentiel énergétique réel",
      description: "Créer l'ouverture et comprendre le processus",
      sections: [
        {
          numero: "0.1",
          titre: "Bienvenue dans la Masterclass",
          sousTitre: "Tu n'es pas seul",
          fonction: "Créer l'ouverture émotionnelle et l'identification.",
          contenu: "As-tu déjà eu l'impression de fonctionner constamment à vide? De toujours manquer d'énergie? De pousser ton système plus loin que ses capacités? D'avoir des journées trop lourdes pour ton niveau énergétique réel?",
          exemple: "Plusieurs personnes pensent que leur problème est le manque de motivation, le manque de discipline ou le manque de volonté. Mais souvent, le vrai problème est une déconnexion énergétique. Les humains ont appris à performer, à produire, à continuer, à répondre aux attentes, sans apprendre à observer leur réalité énergétique réelle.",
          aRetenir: ["Le problème est souvent une déconnexion énergétique", "Chaque expérience possède un coût énergétique", "Une trajectoire énergétique se construit une expérience à la fois"],
          transition: "Voyons ensemble comment fonctionne la Méthode i+.",
        },
        {
          numero: "0.2",
          titre: "Rappel simplifié de la Méthode i+",
          sousTitre: "Les 8 étapes de l'expérience",
          fonction: "Présenter les bases de la Méthode i+.",
          contenu: "La Méthode i+ permet de comprendre que les expériences énergétiques ne commencent pas seulement lorsque nous sommes fatigués. Une expérience commence lorsqu'un déclencheur capte notre attention. Dans la gestion de l'énergie, un déclencheur peut être une fatigue, une douleur, une surcharge mentale, une demande supplémentaire, une émotion, une responsabilité, une relation ou un environnement lourd. À partir du déclencheur, nous interprétons la situation, nous ressentons des émotions, nous prenons des décisions, nous développons des habitudes, nous construisons progressivement une trajectoire énergétique.",
          exemple: "1. Observer\n2. Prédire\n3. Ressentir\n4. Choisir\n5. Planifier\n6. Agir\n7. Évaluer\n8. Apprendre\n\nMême lorsque nous ne les voyons pas consciemment, ces étapes sont toujours présentes dans les expériences énergétiques.",
          aRetenir: ["Les 8 étapes sont toujours présentes dans les expériences énergétiques", "Un déclencheur active le schéma", "Les expériences répétitives influencent l'énergie vitale"],
          question: "Peux-tu identifier les 8 étapes dans une expérience énergétique que tu vis régulièrement?",
          transition: "Maintenant, découvrons le système énergétique humain.",
        },
        {
          numero: "0.3",
          titre: "Règles importantes de la gestion énergétique",
          sousTitre: "Des repères pour comprendre",
          fonction: "Établir les règles de la gestion énergétique.",
          contenu: "Une seule composante menace peut vider rapidement le réservoir énergétique. Une seule composante opportunité peut commencer à stabiliser une trajectoire. Les expériences répétitives influencent l'énergie vitale. Les expériences énergivores répétées augmentent l'usure du système humain. Les expériences énergisantes répétées stabilisent progressivement le système. Les trajectoires énergétiques se construisent une expérience à la fois.",
          aRetenir: ["Une seule menace peut vider le réservoir", "Une seule opportunité peut stabiliser", "Les trajectoires se construisent une expérience à la fois"],
          transition: "Commençons par comprendre le système énergétique humain.",
        },
      ],
    },
    {
      numero: 1,
      titre: "Comprendre le système énergétique humain",
      description: "Le véhicule, l'essence, les trajets, les conditions",
      sections: [
        {
          numero: "1.1",
          titre: "Le réservoir énergétique quotidien",
          sousTitre: "Le véhicule énergétique",
          fonction: "Présenter la métaphore du véhicule.",
          contenu: "Pour comprendre l'énergie humaine, utilisons une métaphore simple : le corps humain fonctionne comme un véhicule. Chaque journée, nous possédons une quantité d'énergie disponible. Comme un niveau d'essence dans un véhicule. Certaines journées le réservoir est plus plein, d'autres le niveau est plus faible.",
          exemple: "Un véhicule bien entretenu, respecté et adapté à sa réalité gardera de meilleures capacités à long terme. Mais un moteur constamment poussé sans récupération, sans adaptation, sans pauses, sans entretien, s'use progressivement.",
          aRetenir: ["L'énergie quotidienne est comme un réservoir d'essence", "Le système humain s'use sous pression constante", "L'entretien préserve les capacités à long terme"],
          question: "Comment décrirais-tu l'état de ton véhicule énergétique?",
        },
        {
          numero: "1.2",
          titre: "Les expériences sont comme des trajets",
          sousTitre: "Le coût énergétique de chaque expérience",
          fonction: "Comprendre que chaque expérience a un coût.",
          contenu: "Chaque expérience ressemble à un trajet. Et avant chaque trajet, certaines questions deviennent importantes : Pourquoi je fais ce trajet? Est-ce que ce trajet vaut le coût énergétique? Est-ce adapté à mon véhicule? Est-ce adapté à mon niveau d'essence? Est-ce adapté aux conditions actuelles? Est-ce adapté à mon état réel?",
          exemple: "Les petits trajets du quotidien demandent peu d'énergie, créent peu d'usure et sont faciles à gérer. Mais les grands trajets énergétiques (surcharge, responsabilités importantes, maladie, douleur chronique, conflits, changements majeurs, pression constante) demandent plus d'énergie, augmentent l'usure du système et nécessitent plus d'adaptation.",
          aRetenir: ["Chaque expérience a un coût énergétique", "Les petits trajets coûtent peu", "Les grands trajets demandent plus d'adaptation"],
          question: "Quels trajets énergétiques fais-tu le plus souvent?",
        },
        {
          numero: "1.3",
          titre: "Les conditions de route énergétiques",
          sousTitre: "Adapter sa conduite aux conditions",
          fonction: "Comprendre l'adaptation aux conditions.",
          contenu: "Un conducteur intelligent n'observe pas seulement son essence et son véhicule. Il observe aussi les conditions de la route. Parfois il faut aller travailler, répondre à certains besoins essentiels, même si la météo est mauvaise et l'énergie plus basse. La personne peut quand même décider de faire le trajet, mais elle devra probablement ralentir, adapter sa conduite, prévoir davantage, protéger son système et gérer ses réserves intelligemment.",
          exemple: "S'il y a une tempête, peu d'essence, beaucoup de fatigue et un moteur instable, est-ce vraiment le bon moment pour faire un trajet non essentiel? Certaines personnes continuent quand même, poussent le système, ignorent les conditions. Et cela augmente souvent la surcharge, l'usure, le stress et les risques. La gestion énergétique consiste aussi à apprendre quel trajet faire, quand le faire, dans quelles conditions le faire.",
          aRetenir: ["Observer les conditions avant de s'engager", "Certaines expériences peuvent attendre", "Adapter ses attentes à la réalité énergétique"],
          question: "Quand les conditions sont difficiles, continues-tu quand même?",
          transition: "Voyons maintenant l'erreur la plus fréquente dans la gestion de l'énergie.",
        },
      ],
    },
    {
      numero: 2,
      titre: "La grande erreur énergétique moderne",
      description: "Fonctionner comme une machine illimitée",
      sections: [
        {
          numero: "2.1",
          titre: "La société de la performance illimitée",
          sousTitre: "Fonctionner comme des machines",
          fonction: "Comprendre le biais de performance constante.",
          contenu: "La société moderne pousse souvent les humains à fonctionner comme des machines illimitées. Les humains apprennent à performer, à produire, à rester disponibles, à continuer malgré les signaux. Mais très peu de personnes apprennent à observer leur tableau de bord énergétique.",
          exemple: "Le corps envoie constamment des signaux : fatigue, tensions, irritabilité, douleurs, surcharge, baisse de motivation. Ce sont des voyants du tableau de bord. Mais plusieurs personnes continuent à accélérer, ignorent les signaux et poussent le moteur davantage.",
          aRetenir: ["Les signaux du corps sont des voyants", "Ignorer les voyants augmente l'usure", "Peu de personnes observent leur tableau de bord"],
          question: "Quels voyants ignores-tu le plus souvent?",
        },
        {
          numero: "2.2",
          titre: "Les faux boosts énergétiques",
          sousTitre: "Stimuler au lieu de récupérer",
          fonction: "Comprendre les faux boosts.",
          contenu: "Certaines personnes utilisent constamment du café, du sucre, de la stimulation, de l'urgence ou de la suractivité. Comme un moteur constamment poussé dans le rouge. Un boost peut parfois aider temporairement. Mais si le système fonctionne constamment avec des stimulants, avec de la pression, avec de l'urgence, le moteur finit souvent par s'user davantage.",
          exemple: "Marc utilise du café chaque matin pour compenser le manque de sommeil. Il fonctionne sous pression constante. Il utilise l'urgence comme moteur. Temporairement, ça fonctionne. À long terme, le système s'use.",
          aRetenir: ["Les faux boosts aident temporairement", "La stimulation constante use le système", "La récupération est la vraie solution"],
          question: "Quels faux boosts utilises-tu le plus souvent?",
          transition: "Découvrons maintenant le principe central de la gestion énergétique.",
        },
      ],
    },
    {
      numero: 3,
      titre: "Le principe central énergétique",
      description: "Chaque expérience doit valoir son coût énergétique",
      sections: [
        {
          numero: "3.1",
          titre: "Pourquoi j'investis mon énergie ici?",
          sousTitre: "La vraie question énergétique",
          fonction: "Établir le principe de décision énergétique.",
          contenu: "Chaque trajet demande de l'essence, de l'usure, de l'énergie et de l'attention. Donc la vraie question devient : Pourquoi j'investis mon énergie ici?",
          exemple: "Les questions importantes : Pourquoi je fais cette expérience? Quels résultats vais-je obtenir? Est-ce utile à court terme? Moyen terme? Long terme? Est-ce aligné avec mes besoins? Est-ce que cette expérience nourrit ma trajectoire? Ou est-ce qu'elle use mon système?",
          aRetenir: ["Chaque expérience a un coût énergétique", "La question clé : pourquoi j'investis mon énergie ici?", "Chaque trajet demande de l'essence, de l'usure, de l'attention"],
          question: "Quelles expériences énergivores ne valent pas réellement leur coût?",
        },
        {
          numero: "3.2",
          titre: "Désirs versus besoins",
          sousTitre: "Investir dans le bon réservoir",
          fonction: "Distinguer désirs et besoins énergétiques.",
          contenu: "Certaines expériences stimulent temporairement mais ne nourrissent pas réellement les besoins humains. Lorsqu'une personne investit constamment son énergie dans les désirs, dans les attentes, dans la performance, dans la comparaison, sans répondre à ses besoins réels, le système finit souvent en surcharge.",
          exemple: "Marc investit son énergie dans la performance et la comparaison. Il répond aux attentes des autres avant ses propres besoins. Son système est constamment en surcharge.",
          aRetenir: ["Désirs et besoins ne sont pas la même chose", "Investir dans les désirs mène à la surcharge", "Répondre aux besoins réels nourrit la trajectoire"],
          question: "Où investis-tu ton énergie? Dans les désirs ou dans les besoins?",
          transition: "Voyons maintenant comment Marc a construit sa trajectoire de surcharge.",
        },
      ],
    },
    {
      numero: 4,
      titre: "Marc et la trajectoire de surcharge",
      description: "Comprendre une trajectoire énergivore",
      sections: [
        {
          numero: "4.1",
          titre: "Le quotidien de Marc",
          sousTitre: "Un système constamment poussé",
          fonction: "Présenter le personnage et sa trajectoire.",
          contenu: "Marc a 37 ans. Il veut performer, répondre à tout, aider tout le monde, ne jamais ralentir. Il croit qu'il doit constamment continuer. Il dort peu, surcharge ses journées, accepte trop de responsabilités, ignore sa fatigue et utilise souvent du café pour continuer. Il ne regarde presque jamais son niveau énergétique réel.",
          exemple: "Progressivement, Marc développe : irritabilité, fatigue chronique, baisse de motivation, procrastination, surcharge mentale, frustration, difficulté d'adaptation. Sa trajectoire devient une trajectoire de surcharge énergétique.",
          aRetenir: ["Marc pousse son système au-delà de ses capacités", "Les conséquences apparaissent progressivement", "La trajectoire de surcharge se renforce d'elle-même"],
          question: "Te reconnais-tu dans certains aspects du quotidien de Marc?",
        },
        {
          numero: "4.2",
          titre: "Ce que Marc découvre",
          sousTitre: "La prise de conscience",
          fonction: "Montrer la prise de conscience.",
          contenu: "Marc découvre progressivement qu'il répète des expériences énergivores, qu'il pousse constamment son moteur, qu'il ignore les voyants et qu'il vide constamment ses réserves. Il réalise que certaines expériences ne valent pas réellement leur coût énergétique.",
          exemple: "Marc commence progressivement à observer son tableau de bord énergétique, ajuster ses attentes, prévoir les imprévus, protéger ses réserves et adapter ses trajets.",
          aRetenir: ["La prise de conscience est la première étape", "Marc réalise que certaines expériences ne valent pas leur coût", "Observer son tableau de bord change tout"],
          transition: "Voyons comment Marc reconnecte avec son énergie.",
        },
      ],
    },
    {
      numero: 5,
      titre: "Reconnecter avec son énergie",
      description: "Réserves, expériences énergisantes, nouvelles questions",
      sections: [
        {
          numero: "5.1",
          titre: "Les réserves énergétiques",
          sousTitre: "Protéger sa marge d'adaptation",
          fonction: "Comprendre l'importance des réserves.",
          contenu: "Les réserves servent à gérer les imprévus. Une personne qui utilise constamment toute son énergie n'a plus de marge d'adaptation. Le moindre imprévu devient plus lourd, plus stressant, plus difficile à gérer.",
          exemple: "Marc prévoit maintenant 20% de réserve dans sa journée. Quand un imprévu arrive, il a de l'énergie pour y faire face sans surcharger son système.",
          aRetenir: ["Les réserves protègent contre les imprévus", "Utiliser 100% de son énergie = aucune marge", "Prévoir de la réserve est une stratégie intelligente"],
          question: "Quelle marge de réserve gardes-tu dans ta journée?",
        },
        {
          numero: "5.2",
          titre: "Les expériences énergisantes",
          sousTitre: "Nourrir sa trajectoire",
          fonction: "Choisir des expériences qui nourrissent.",
          contenu: "Marc commence à éliminer certaines expériences énergivores. Il choisit davantage ses trajets. Il limite certaines relations. Il respecte davantage ses limites. Il répète des expériences énergisantes.",
          exemple: "Les nouvelles questions de Marc.\n\nAvant : \"Comment puis-je en faire plus?\"\nMaintenant : \"Est-ce que cette expérience vaut réellement son coût énergétique?\" \"Est-ce le bon moment?\" \"Est-ce adapté à mon état actuel?\" \"Est-ce que mon véhicule peut réellement faire ce trajet aujourd'hui?\"",
          aRetenir: ["Les expériences énergisantes nourrissent la trajectoire", "Éliminer les expériences énergivores protège le système", "Changer ses questions change ses choix"],
          question: "Quelles expériences énergisantes veux-tu répéter davantage?",
          transition: "Découvrons maintenant la vraie transformation énergétique.",
        },
      ],
    },
    {
      numero: 6,
      titre: "La vraie transformation énergétique",
      description: "Vivre selon sa réalité énergétique réelle",
      sections: [
        {
          numero: "6.1",
          titre: "Vivre selon son potentiel énergétique réel",
          sousTitre: "Pas seulement se reposer davantage",
          fonction: "Comprendre la vraie transformation.",
          contenu: "La gestion de l'énergie ne consiste pas seulement à se reposer davantage. Elle consiste surtout à apprendre à vivre selon sa réalité énergétique réelle. La personne découvre progressivement son potentiel réel, ses limites réelles, ses besoins réels, les expériences qui nourrissent sa trajectoire, les expériences qui usent son système, les relations énergisantes, les environnements énergivores et les trajets qui valent réellement le coût énergétique.",
          exemple: "Respecter son énergie n'est pas de la faiblesse. C'est protéger le véhicule qui permet de vivre sa trajectoire humaine.",
          aRetenir: ["La transformation = vivre selon sa réalité énergétique", "Respecter son énergie n'est pas de la faiblesse", "Protéger le véhicule permet de durer"],
          question: "Qu'est-ce que la vraie transformation énergétique signifie pour toi?",
        },
        {
          numero: "6.2",
          titre: "Conclusion",
          sousTitre: "Tu es devenu un i+",
          fonction: "Valoriser l'évolution.",
          contenu: "La trajectoire énergétique ultime n'est pas d'aller le plus vite possible. C'est d'être capable de vivre de belles trajectoires durablement. Vivre selon son potentiel énergétique réel. Respecter son système humain. Choisir des expériences alignées. Protéger son énergie vitale. Adapter ses trajets. Ajuster sa conduite. Entretenir son véhicule. Parce qu'une trajectoire énergétique se construit un trajet à la fois.",
          aRetenir: ["Tu comprends tes expériences énergétiques", "Tu sais transformer les menaces en opportunités", "Tu ajustes ta trajectoire une expérience à la fois"],
        },
      ],
    },
  ],
};
