import type { MasterclassData } from "./index";

export const masterclassMethode: MasterclassData = {
  slug: "methode-i+",
  thematique: "Méthode i+",
  icon: "🎓",
  personnage: "Marc",
  parties: [
    {
      numero: 0,
      titre: "Introduction — Bienvenue dans la Méthode i+",
      description: "Créer l'ouverture et comprendre le processus",
      sections: [
        {
          numero: "0.1",
          titre: "Bienvenue chez i23",
          sousTitre: "Tu n'es pas seul",
          fonction: "Créer l'ouverture émotionnelle et l'identification.",
          contenu: "Si tu es ici, c'est probablement parce que tu vis des expériences qui se répètent. Des expériences qui te limitent, te bloquent ou te drainent. Tu n'es pas seul. Plusieurs personnes vivent des schémas répétitifs sans savoir comment les transformer. La Méthode i+ existe pour ça : t'aider à comprendre ce qui se passe réellement dans tes expériences et te donner les outils pour les modifier.",
          exemple: "Tu répètes peut-être certains patterns : procrastiner, éviter, sur-réagir, te comparer, te juger, dire oui quand tu veux dire non. Ces expériences se répètent parce que les schémas qui les génèrent n'ont jamais été identifiés ni modifiés.",
          aRetenir: ["Les expériences répétitives sont des schémas modifiables", "Tu n'es pas seul à vivre ça", "La Méthode i+ donne les outils pour transformer"],
          transition: "Découvrons ce qu'est une expérience.",
        },
        {
          numero: "0.2",
          titre: "Qu'est-ce qu'une expérience?",
          sousTitre: "La base de la Méthode i+",
          fonction: "Définir ce qu'est une expérience.",
          contenu: "Dans la Méthode i+, une expérience est tout ce qui se passe à partir du moment où un déclencheur capte ton attention. Chaque expérience suit les mêmes 8 étapes, même si tu n'en es pas conscient. Comprendre ces étapes te donne prise sur ce que tu vis.",
          exemple: "Exemple : tu reçois un courriel urgent. Ce déclencheur active une expérience. Tu observes le message, tu prédis ce que ça implique, tu ressens une émotion, tu choisis comment réagir, tu planifies, tu agis, tu évalues le résultat, tu apprends. Ces 8 étapes se sont produites, même si tu ne les as pas remarquées consciemment.",
          aRetenir: ["Une expérience commence par un déclencheur", "Chaque expérience suit les 8 étapes", "Comprendre les étapes donne prise sur l'expérience"],
          question: "Quelle expérience répétitive voudrais-tu comprendre?",
          transition: "Voyons les 8 étapes en détail.",
        },
      ],
    },
    {
      numero: 1,
      titre: "Les 8 étapes de l'expérience",
      description: "Comprendre le schéma d'expérience",
      sections: [
        {
          numero: "1.1",
          titre: "1. Observer",
          sousTitre: "Percevoir les informations",
          fonction: "Expliquer l'étape Observer.",
          contenu: "Observer, c'est percevoir et sélectionner les informations dans une situation. C'est la première étape de chaque expérience. Ce que tu observes influence tout le reste. Tes perceptions sont subjectives : deux personnes dans la même situation observent des choses différentes.",
          exemple: "Marc observe une tâche à faire. Il perçoit : \"C'est énorme.\" Sa collègue observe la même tâche et perçoit : \"C'est faisable par étapes.\" Même situation, observations différentes, expériences différentes.",
          aRetenir: ["Observer est subjectif", "Ce que tu observes influence tout le schéma", "Tu peux apprendre à observer différemment"],
          question: "Qu'est-ce que tu observes en premier dans une situation difficile?",
        },
        {
          numero: "1.2",
          titre: "2. Prédire",
          sousTitre: "Créer des scénarios et anticipations",
          fonction: "Expliquer l'étape Prédire.",
          contenu: "Prédire, c'est créer des scénarios, des interprétations et des anticipations. Ton cerveau prédit constamment ce qui va se passer. Ces prédictions peuvent être réalistes ou non. Elles influencent directement ce que tu ressens et ce que tu choisis.",
          exemple: "Marc prédit : \"Je vais échouer.\" Cette prédiction génère du stress avant même qu'il commence. S'il prédit : \"Je peux essayer et voir\", l'expérience est complètement différente.",
          aRetenir: ["Les prédictions ne sont pas des faits", "Une prédiction négative peut créer l'expérience négative", "Tu peux apprendre à prédire de façon plus réaliste"],
          question: "Quelles prédictions fais-tu qui limitent tes expériences?",
        },
        {
          numero: "1.3",
          titre: "3. Ressentir",
          sousTitre: "Vivre les émotions",
          fonction: "Expliquer l'étape Ressentir.",
          contenu: "Ressentir, c'est vivre les émotions et la charge émotive liées à l'expérience. Les émotions sont des informations, pas des fautes. Identifier clairement chaque émotion est crucial. Accepter ses émotions sans jugement aide à mieux les gérer.",
          exemple: "Marc ressent du stress, de la frustration et du découragement. S'il ignore ces émotions, elles influencent quand même ses choix. S'il les identifie, il peut choisir comment les gérer.",
          aRetenir: ["Les émotions sont des informations", "Ignorer une émotion ne la fait pas disparaître", "Identifier ce que tu ressens te donne du pouvoir sur l'expérience"],
          question: "Quelle émission évites-tu le plus souvent?",
        },
        {
          numero: "1.4",
          titre: "4. Choisir",
          sousTitre: "Prendre des décisions",
          fonction: "Expliquer l'étape Choisir.",
          contenu: "Choisir, c'est prendre des décisions selon son identité, ses besoins, ses valeurs, la réalité, les autres et l'environnement. Aligner ses décisions avec ses valeurs renforce l'authenticité. Chaque choix influence le résultat de l'expérience.",
          exemple: "Marc choisit de reporter la tâche. Ce choix aligné avec la peur, pas avec ses valeurs. S'il choisit de commencer petit, le choix est aligné avec sa valeur de progression.",
          aRetenir: ["Chaque choix influence le résultat", "Aligner ses choix avec ses valeurs renforce l'authenticité", "Tu peux choisir différemment même sous pression émotionnelle"],
          question: "Quel choix fais-tu souvent qui n'est pas aligné avec tes valeurs?",
        },
        {
          numero: "1.5",
          titre: "5. Planifier",
          sousTitre: "Préparer les stratégies",
          fonction: "Expliquer l'étape Planifier.",
          contenu: "Planifier, c'est préparer les stratégies liées aux décisions. Définir des objectifs précis et atteignables est essentiel. Planifier chaque action avec soin évite les imprévus. Anticiper les obstacles permet de les surmonter plus facilement.",
          exemple: "Marc ne planifie pas. Il improvise et se fait surprendre. S'il planifie : \"Je fais 15 minutes sur cette tâche à 10h\", il augmente ses chances de réussite.",
          aRetenir: ["Planifier augmente les chances de réussite", "Des objectifs précis sont plus efficaces que des intentions vagues", "Anticiper les obstacles permet de s'y préparer"],
          question: "Qu'est-ce qui arrive quand tu ne planifies pas?",
        },
        {
          numero: "1.6",
          titre: "6. Agir",
          sousTitre: "Mettre en application",
          fonction: "Expliquer l'étape Agir.",
          contenu: "Agir, c'est mettre les stratégies en application dans le quotidien. Intégrer les actions dans une routine quotidienne facilite la cohérence. Maintenir la régularité est crucial pour des résultats durables. L'action précède souvent la motivation, pas l'inverse.",
          exemple: "Marc attend d'être motivé pour agir. La motivation ne vient pas. S'il agit d'abord (5 minutes), la motivation suit souvent.",
          aRetenir: ["L'action précède souvent la motivation", "La régularité est plus importante que l'intensité", "Chaque petite action compte"],
          question: "Quand est-ce que tu attends la motivation avant d'agir?",
        },
        {
          numero: "1.7",
          titre: "7. Évaluer",
          sousTitre: "Observer les résultats",
          fonction: "Expliquer l'étape Évaluer.",
          contenu: "Évaluer, c'est observer les résultats des actions et de l'expérience. Observer attentivement les résultats permet d'ajuster les stratégies. Comparer les résultats avec les attentes initiales aide à évaluer l'efficacité. Interpréter les résultats de manière objective évite les biais.",
          exemple: "Marc évalue : \"J'ai échoué.\" Mais objectivement, il a commencé la tâche, ce qui est un progrès. S'il évalue objectivement, il voit une progression.",
          aRetenir: ["Évaluer objectivement évite les biais négatifs", "Les petits progrès sont des résultats valables", "Évaluer permet d'ajuster pour la prochaine expérience"],
          question: "Comment évalues-tu habituellement tes résultats?",
        },
        {
          numero: "1.8",
          titre: "8. Apprendre",
          sousTitre: "Intégrer les apprentissages",
          fonction: "Expliquer l'étape Apprendre.",
          contenu: "Apprendre, c'est intégrer les apprentissages et ajuster les prochaines expériences. Intégrer les succès et les échecs permet une évolution continue. Tirer des leçons de chaque situation évite de répéter les mêmes erreurs. Adopter une attitude d'apprentissage continu favorise le développement personnel.",
          exemple: "Marc apprend : \"Je procrastine toujours.\" Cet apprentissage renforce le schéma. S'il apprend : \"Quand je commence petit, j'arrive à avancer\", il oriente sa trajectoire vers le changement.",
          aRetenir: ["Ce que tu apprends renforce ou transforme ta trajectoire", "Les apprentissages négatifs renforcés deviennent des croyances", "Tu peux choisir ce que tu apprends de chaque expérience"],
          question: "Que répètes-tu comme apprentissage après tes expériences?",
          transition: "Maintenant que tu connais les 8 étapes, découvrons les niveaux de la Méthode i+.",
        },
      ],
    },
    {
      numero: 2,
      titre: "Les 3 sphères : i, 2, 3",
      description: "Individuel, Relationnel, Environnemental",
      sections: [
        {
          numero: "2.1",
          titre: "La sphère i — Individuel",
          sousTitre: "Relation avec soi",
          fonction: "Expliquer le niveau i.",
          contenu: "La sphère i représente ta relation avec toi-même. Ce qui est personnel, qui ne touche pas directement les autres. Tes pensées, tes émotions, tes choix personnels, ta santé, ton énergie, ta confiance en toi. Apprendre à se respecter est la base de la sphère i.",
          exemple: "Marc se juge constamment. Il se compare aux autres. Il ignore ses besoins. Ces expériences se situent dans la sphère i. Transformer ces schémas commence par la relation avec soi-même.",
          aRetenir: ["La sphère i est la fondation", "Sans respect de soi, les autres sphères souffrent", "Transformer les schémas individuels change tout le système"],
          question: "Quelles expériences de la sphère i voudrais-tu transformer?",
        },
        {
          numero: "2.2",
          titre: "La sphère 2 — Relationnel",
          sousTitre: "Les autres êtres humains",
          fonction: "Expliquer le niveau 2.",
          contenu: "La sphère 2 représente ta relation avec les autres. Les relations, les interactions sociales, la communication, les conflits, le soutien. Développer des relations plus saines passe par comprendre les schémas relationnels.",
          exemple: "Marc évite les conflits. Il dit oui quand il veut dire non. Il se sent responsable des émotions des autres. Ces expériences se situent dans la sphère 2. Transformer ces schémas améliore toutes ses relations.",
          aRetenir: ["Les schémas relationnels se répètent aussi", "Comprendre ses schémas relationnels améliore les interactions", "Les relations saines commencent par une relation saine avec soi"],
          question: "Quels schémas relationnaires répètes-tu?",
        },
        {
          numero: "2.3",
          titre: "La sphère 3 — Environnemental",
          sousTitre: "Tout ce qui n'est pas humain",
          fonction: "Expliquer le niveau 3.",
          contenu: "La sphère 3 représente ta relation avec l'environnement. Le contexte, le milieu, les lieux, les ressources, les conditions de vie, le travail, les finances. Tout ce qui n'est pas humain. Adapter son environnement soutient les trajectoires de changement.",
          exemple: "Marc travaille dans un environnement bruyant et exigeant. Son horaire est surchargé. Il n'a pas d'espace personnel. Ces expériences se situent dans la sphère 3. Adapter son environnement réduit les déclencheurs externes.",
          aRetenir: ["L'environnement influence les expériences", "Adapter son environnement réduit les menaces externes", "Les trois sphères interagissent constamment"],
          question: "Quels éléments de ton environnement rendent tes expériences plus difficiles?",
          transition: "Voyons maintenant les concepts clés de la Méthode i+.",
        },
      ],
    },
    {
      numero: 3,
      titre: "Les concepts clés",
      description: "Déclencheurs, menaces, opportunités, trajectoires",
      sections: [
        {
          numero: "3.1",
          titre: "Le déclencheur",
          sousTitre: "Ce qui active une expérience",
          fonction: "Expliquer le concept de déclencheur.",
          contenu: "Un déclencheur est ce qui active ton expérience. Il peut être externe (une situation, un événement, une personne) ou interne (une pensée, une émotion, une sensation physique). Chaque expérience commence par un déclencheur. Identifier tes déclencheurs fréquents est la première étape pour comprendre tes schémas.",
          exemple: "Déclencheurs de Marc : recevoir une tâche urgente, se faire critiquer, se réveiller fatigué, voir sa liste de tâches, entendre un collègue se plaindre. Chaque déclencheur active un schéma différent.",
          aRetenir: ["Chaque expérience commence par un déclencheur", "Les déclencheurs peuvent être externes ou internes", "Identifier tes déclencheurs fréquents est la première étape"],
          question: "Quels sont tes déclencheurs les plus fréquents?",
        },
        {
          numero: "3.2",
          titre: "La menace",
          sousTitre: "Ce qui bloque, surcharge ou limite",
          fonction: "Expliquer le concept de menace.",
          contenu: "Une menace est une composante du schéma qui bloque, surcharge ou limite. Les menaces se retrouvent dans chaque étape de l'expérience. Une seule menace peut affecter tout le schéma. Les menaces sont souvent des croyances, des pensées automatiques ou des comportements appris.",
          exemple: "Menaces dans le schéma de Marc :\nObserver : \"C'est trop gros.\"\nPrédire : \"Je vais échouer.\"\nRessentir : stress, culpabilité\nChoisir : éviter\nPlanifier : aucune stratégie\nAgir : procrastiner\nÉvaluer : \"J'ai encore échoué.\"\nApprendre : \"Je suis comme ça.\"",
          aRetenir: ["Les menaces se retrouvent dans chaque étape", "Une seule menace peut affecter tout le schéma", "Les menaces sont souvent des croyances ou pensées automatiques"],
          question: "Quelles menaces reconnais-tu dans tes expériences?",
        },
        {
          numero: "3.3",
          titre: "L'opportunité",
          sousTitre: "Ce qui aide, soutient ou ouvre une possibilité",
          fonction: "Expliquer le concept d'opportunité.",
          contenu: "Une opportunité est une composante du schéma qui aide, soutient ou ouvre une possibilité. Les opportunités existent dans chaque expérience, même si elles ne sont pas activées. Activer une opportunité transforme l'expérience. Les Outils i+ servent précisément à transformer les menaces en opportunités.",
          exemple: "Opportunités pour Marc :\nObserver : \"Je peux découper la tâche.\"\nPrédire : \"Commencer petit est suffisant.\"\nRessentir : calme, motivation légère\nChoisir : commencer maintenant\nPlanifier : bloc de 10 minutes\nAgir : première étape\nÉvaluer : \"J'ai avancé.\"\nApprendre : \"Commencer fonctionne.\"",
          aRetenir: ["Les opportunités existent toujours", "Activer une opportunité transforme l'expérience", "Les Outils i+ servent à activer les opportunités"],
          question: "Quelles opportunités pourrais-tu activer dans tes expériences?",
        },
        {
          numero: "3.4",
          titre: "La trajectoire",
          sousTitre: "L'accumulation des expériences dans le temps",
          fonction: "Expliquer le concept de trajectoire.",
          contenu: "Une trajectoire est l'accumulation des expériences dans le temps. Les expériences répétées créent une trajectoire. Les expériences répétitives avec des menaces créent une trajectoire descendante. Les expériences répétées avec des opportunités créent une trajectoire ascendante. Modifier une seule expérience modifie la trajectoire.",
          exemple: "Marc répète : procrastination → retard → stress → fatigue → manque de confiance → procrastination. C'est une trajectoire qui se renforce. Mais modifier une seule expérience (commencer petit au lieu de procrastiner) oriente vers une trajectoire différente.",
          aRetenir: ["Les expériences répétées créent une trajectoire", "Les trajectoires peuvent être descendantes ou ascendantes", "Modifier une seule expérience modifie la trajectoire"],
          question: "Quelle trajectoire observes-tu dans ta vie actuellement?",
          transition: "Découvrons maintenant les outils pour transformer les menaces en opportunités.",
        },
      ],
    },
    {
      numero: 4,
      titre: "Les Outils i+",
      description: "Transformer les menaces en opportunités",
      sections: [
        {
          numero: "4.1",
          titre: "L'Outil Schéma i+",
          sousTitre: "Le coeur du système",
          fonction: "Présenter l'Outil Schéma i+.",
          contenu: "L'Outil Schéma i+ est le coeur du système. Il te permet de décortiquer une expérience en identifiant les 8 étapes, de repérer les menaces dans chaque étape, de choisir des opportunités pour remplacer les menaces, de créer un nouveau schéma et de préparer l'expérimentation. C'est l'outil principal de transformation dans i23.",
          exemple: "Marc utilise l'Outil Schéma i+ pour décortiquer son expérience de procrastination. Il identifie les menaces dans chaque étape et choisit les opportunités correspondantes. Il crée un nouveau schéma qu'il va expérimenter.",
          aRetenir: ["L'Outil Schéma i+ est le coeur du système", "Il permet de décortiquer, identifier et transformer", "Tu peux l'utiliser pour n'importe quelle expérience"],
          question: "Quelle expérience voudrais-tu décortiquer avec l'Outil Schéma i+?",
        },
        {
          numero: "4.2",
          titre: "Les Outils i+ par étape",
          sousTitre: "Un outil pour chaque étape",
          fonction: "Présenter les Outils i+ par étape.",
          contenu: "Pour chaque étape de la Méthode i+, il existe des outils spécifiques qui t'aident à transformer une menace en opportunité. Chaque outil est un formulaire interactif qui te guide dans la transformation. 8 étapes, 10 outils par étape, 80 outils au total.",
          exemple: "Étape 1 (Observer) : Scan d'observation, Validation des perceptions, Faits vs interprétations...\nÉtape 2 (Prédire) : Scan des scénarios, Validation des prédictions...\nÉtape 4 (Choisir) : Alignement avec mes valeurs, Clarification des choix...",
          aRetenir: ["Un outil pour chaque étape", "80 outils au total", "Chaque outil guide la transformation menace → opportunité"],
          question: "Quelle étape a le plus besoin d'un outil selon toi?",
          transition: "Voyons maintenant les Groupes i+.",
        },
      ],
    },
    {
      numero: 5,
      titre: "Les Groupes i+",
      description: "Partager, expérimenter, progresser ensemble",
      sections: [
        {
          numero: "5.1",
          titre: "Comment fonctionnent les Groupes i+",
          sousTitre: "Rencontres d'échange et d'expérimentation",
          fonction: "Présenter les Groupes i+.",
          contenu: "Les Groupes i+ sont des rencontres d'échange et d'expérimentation sur Zoom. Ils soutiennent la répétition, les ajustements et l'intégration de la Méthode i+. Chaque rencontre dure environ 60 minutes et suit un déroulement structuré : accueil, retour sur les expérimentations, mini contenu théorique, utilisation d'un outil, discussion, action concrète et conclusion.",
          exemple: "Marc participe à un Groupe i+ sur la gestion du temps. Il partage ses expériences de la semaine, découvre les stratégies des autres participants et repart avec une action concrète à tester.",
          aRetenir: ["Les Groupes i+ soutiennent l'expérimentation", "Partager renforce l'apprentissage", "Chaque rencontre suit un déroulement structuré"],
          question: "Comment le partage pourrait t'aider dans ton parcours?",
        },
        {
          numero: "5.2",
          titre: "Les règles des Groupes i+",
          sousTitre: "Un cadre respectueux et concret",
          fonction: "Présenter les règles des Groupes i+.",
          contenu: "Les Groupes i+ suivent des règles claires : le climat doit être respectueux, les échanges doivent rester concrets, les animateurs doivent recentrer les discussions, les outils doivent être utilisés régulièrement, les participants doivent repartir avec une action et les groupes doivent soutenir l'expérimentation.",
          aRetenir: ["Le respect est la base", "Les échanges restent concrets", "Chacun repart avec une action"],
          question: "Qu'est-ce qui te motive à partager dans un groupe?",
          transition: "Découvrons maintenant l'expérimentation i+.",
        },
      ],
    },
    {
      numero: 6,
      titre: "L'expérimentation i+",
      description: "Appliquer le nouveau schéma dans le quotidien",
      sections: [
        {
          numero: "6.1",
          titre: "Expérimenter le nouveau schéma",
          sousTitre: "Le changement réel commence",
          fonction: "Comprendre l'expérimentation.",
          contenu: "L'expérimentation i+, c'est appliquer ton nouveau schéma dans tes expériences quotidiennes. Quand le déclencheur se présente, tu vis l'expérience différemment. Tu observes les résultats. Tu ajustes. Tu réexpérimentes. C'est un cycle continu de modification, d'observation et d'ajustement.",
          exemple: "Marc a créé un nouveau schéma pour gérer la procrastination. Quand le déclencheur se présente (une tâche importante), il applique son nouveau schéma (commencer petit, 5 minutes). Il observe le résultat. Il ajuste si nécessaire. Il réexpérimente.",
          aRetenir: ["L'expérimentation se vit dans le quotidien", "C'est un cycle : modifier, observer, ajuster", "Chaque expérimentation améliore la trajectoire"],
          question: "Quand penses-tu que ton déclencheur se présentera la prochaine fois?",
        },
        {
          numero: "6.2",
          titre: "Les notes d'ajustement",
          sousTitre: "Le lien entre les expériences",
          fonction: "Comprendre les notes d'ajustement.",
          contenu: "Les notes d'ajustement servent de lien entre les expériences. Elles permettent d'expliquer les ajustements, de comprendre ce qui a fonctionné, de comprendre les difficultés, de préparer le prochain schéma et de construire la trajectoire. Schéma expérimenté → Notes d'ajustement → Nouveau schéma à expérimenter.",
          exemple: "Marc expérimente son nouveau schéma. Il note : \"Commencer par 5 minutes a fonctionné. Le matin est plus facile. L'après-midi, la fatigue rend le démarrage plus difficile. Je vais ajuster : 5 minutes le matin, pause l'après-midi.\"",
          aRetenir: ["Les notes d'ajustement relient les expériences", "Elles documentent ce qui fonctionne", "Elles préparent la prochaine expérimentation"],
          question: "Comment pourrais-tu documenter tes ajustements?",
        },
        {
          numero: "6.3",
          titre: "La trajectoire i+",
          sousTitre: "Se construit une expérience à la fois",
          fonction: "Comprendre la trajectoire i+.",
          contenu: "La trajectoire i+ se construit une expérience à la fois. Chaque expérience transformée améliore la trajectoire. Chaque expérimentation ajuste la direction. Chaque ajustement affiné le processus. La trajectoire n'est pas une ligne droite. C'est une progression avec des avancées, des reculs et des ajustements. L'important est la direction générale, pas la perfection.",
          exemple: "Marc a transformé son expérience de procrastination. Puis son expérience de surcharge. Puis sa communication au travail. Chaque transformation améliore sa trajectoire globale. Il n'est pas parfait, mais il progresse.",
          aRetenir: ["La trajectoire se construit une expérience à la fois", "La direction générale est plus importante que la perfection", "Chaque transformation améliore la trajectoire"],
          question: "Quelle est la direction que tu veux donner à ta trajectoire?",
        },
        {
          numero: "6.4",
          titre: "Les valeurs i+",
          sousTitre: "Chaque valeur émerge de la Méthode i+",
          fonction: "Présenter les valeurs i+.",
          contenu: "Les valeurs i+ ne sont pas une liste séparée. Elles émergent des étapes fondatrices de la Méthode i+ :\n\nAdaptation (Observer + Prédire) : s'adapter aux informations et aux scénarios.\nÉvolution (Prédire + Apprendre) : évoluer à travers les prédictions et les apprentissages.\nRespect (Ressentir + Choisir) : respecter ses émotions et ses choix.\nContribution (Choisir + Planifier) : contribuer par ses choix et ses actions.\nCollaboration (Planifier + Agir) : collaborer en planifiant et agissant ensemble.\nImpact positif (Évaluer + Apprendre) : créer un impact positif en évaluant et en apprenant.",
          aRetenir: ["Les valeurs émergent des étapes de la méthode", "Chaque valeur est liée à deux étapes", "Vivre les valeurs, c'est vivre la Méthode i+"],
          question: "Quelle valeur résonne le plus avec toi?",
          transition: "Tu es maintenant prêt à commencer ton parcours i+.",
        },
      ],
    },
    {
      numero: 7,
      titre: "Conclusion — Tu deviens un i+",
      description: "Intégrer et commencer le parcours",
      sections: [
        {
          numero: "7.1",
          titre: "Ce que tu as appris",
          sousTitre: "Les bases de la Méthode i+",
          fonction: "Récapituler les apprentissages.",
          contenu: "Tu connais maintenant les bases de la Méthode i+ : les 8 étapes de l'expérience, les 3 sphères (i, 2, 3), les déclencheurs, les menaces et les opportunités, les trajectoires, les Outils i+ (incluant l'Outil Schéma i+), les Groupes i+ et l'expérimentation i+. Ces bases te donnent un cadre pour comprendre et transformer n'importe quelle expérience.",
          aRetenir: ["Les 8 étapes sont toujours présentes", "Les menaces peuvent être transformées en opportunités", "Les trajectoires se construisent une expérience à la fois"],
        },
        {
          numero: "7.2",
          titre: "La prochaine étape",
          sousTitre: "Choisir une thématique",
          fonction: "Orienter vers la suite du parcours.",
          contenu: "Maintenant que tu comprends la Méthode i+, la prochaine étape est de choisir une thématique que tu veux travailler. L'IA te recommandera des Masterclass selon ton bilan, tes priorités et tes besoins. Chaque Masterclass thématique approfondit la méthode dans un domaine spécifique de ta vie. Tu peux aussi choisir librement la thématique qui te parle le plus.",
          exemple: "Marc complète le quiz de la MC Méthode i+. Il obtient le Badge Méthode i+. Les Masterclass thématiques se débloquent. L'IA lui recommande Gestion de l'énergie selon son bilan. Il commence sa première Masterclass thématique.",
          aRetenir: ["Le Badge Méthode i+ débloque les MC thématiques", "L'IA recommande selon ton bilan", "Tu choisis la thématique qui te parle"],
          consigne: "Complète le quiz pour valider ta compréhension et obtenir ton Badge Méthode i+.",
        },
      ],
    },
  ],
};
